### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Ysmword** [mengzhuo/cookiestxt#1]
我从chrome中将cookie文件拿出来了，并且读取文件内容，放到cookiestxt.Parse函数中，报出的错误：invalid syntax
f, err := os.Open("./Cookies")
if err != nil {
	log.Println(err)
	return
}
	defer f.Close()
cl, err := cookiestxt.Parse(f)
if err != nil {
	log.Println(err)
	return
}
log.Println(cl)

**Comment by mengzhuo** [comment]
invalid syntax 是你的代码语法错误不是库的问题
